import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Leandro Licata Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-4">
        <div className="row">
          <div className="col-md-3">
            {/* <Image
              src="/images/Ghost.jpg"
              alt="XD"
              width={300}
              height={200}
              className="float-left mr-3"
            /> */}
          </div>
          <div className="col-md-9 text-center">
            <h1 className="text-name">Leandro Nicolas Licata</h1>
            <h2 className="mb-4 text-name">Full Stack Web Developer</h2>
            <div className="my-5">
              <a href="#" className="download-button mb-4">
                Download Resume
              </a>
            </div>
            <br />
            <br />
            <h3 className="text-description">About me</h3>
            <p className="text-description">
              Soy un apasionado desarrollador web con experiencia en tecnologías
              como HTML, CSS, JavaScript, React, Node.js y MongoDB.
            </p>
            <p className="text-description">
              Me encanta trabajar en equipo, aprender nuevas tecnologías y crear
              soluciones innovadoras.
            </p>
            <p className="text-description">
              Siempre estoy buscando nuevos desafíos y colaboraciones con
              equipos creativos e innovadores para seguir mejorando mis
              habilidades en el desarrollo de aplicaciones web.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
