import Head from "next/head";
// import { Inter } from "@next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Leandro Licata Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mt-4 font">
        <div className="row text-center">
          <h1 className="text-success">Leandro Nicolas Licata</h1>
          <h2 className="text-info mb-4">Full Stack Web Developer</h2>
          <div className="my-5">
            <a href="#" className="btn btn-outline-light mb-4">
              Download Resume
            </a>
          </div>

          <h3 className="text-secondary">About me</h3>
          <p className="">
            Soy un apasionado desarrollador web con experiencia en tecnologías
            como HTML, CSS, JavaScript, React, Node.js y MongoDB.
          </p>
          <p className="">
            Me encanta trabajar en equipo, aprender nuevas tecnologías y crear
            soluciones innovadoras.
          </p>
          <p className="">
            Siempre estoy buscando nuevos desafíos y colaboraciones con equipos
            creativos e innovadores para seguir mejorando mis habilidades en el
            desarrollo de aplicaciones web.
          </p>
          <i className="fab fa-react fa-3x"></i>
        </div>
      </div>
    </>
  );
}
