import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Leandro Licata Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-2Q/p5CtS5w2QOu5mGPTV7z4Y4y4Jm91ctd21BL/YV7lvLIrZDKw8Zx6msAaG69JssvIyW93P8a6LvSwJh1zHA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <div className="container mt-4 font">
        <div className="row text-center">
          <h1 className="text-success">Leandro Nicolas Licata</h1>
          <h2 className="text-info mb-4">Full Stack Web Developer</h2>
          <div className="my-5">
            <a href="#" className="btn btn-outline-light mb-4">
              Download Resume
            </a>
          </div>

          <h3 className="text-secondary">About me</h3>
          <p className="">
            Soy un apasionado desarrollador web con experiencia en tecnologías
            como HTML, CSS, JavaScript, React, Node.js y MongoDB.
          </p>
          <p className="">
            Me encanta trabajar en equipo, aprender nuevas tecnologías y crear
            soluciones innovadoras.
          </p>
          <p className="">
            Siempre estoy buscando nuevos desafíos y colaboraciones con equipos
            creativos e innovadores para seguir mejorando mis habilidades en el
            desarrollo de aplicaciones web.
          </p>
          <i className="fab fa-react fa-3x"></i>
        </div>
      </div>
      <div className="text-center mt-4 font">
        <h3 className="text-primary">Tecnologías</h3>
        <h4 className="text-secondary">Front-end:</h4>
        <p>HTML, CSS, JavaScript, React, Redux.</p>{" "}
        <h4 className="text-secondary">Back-end:</h4>{" "}
        <p>
          Node.js, Express, MongoDB, PostgreSQL, Mongoose, Sequelize,
          Cloudinary.{" "}
        </p>
        <h4 className="text-secondary"> Herramientas:</h4>{" "}
        <p>Git, GitHub, VS Code, Insomnia.</p>
      </div>
    </>
  );
}
